#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org
 
START=99
STOP=15
 
start() {        
        echo start
        cd /root/pythonwww
        nohup python3 -m http.server 18888 --cgi &
}                 
 
stop() {          
        echo stop
        # commands to kill application 
        process_id=$(ps |grep python3 |grep http.server |grep -v "grep" | awk '{print $1}')
        if [[ ! -z "$process_id" ]]
        then
            kill -9 $process_id
        else
            echo empty
        fi
        mv /root/pythonwww/nohup.out /root/pythonwww/nohup.out.bak
}
